version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
    depends_on:
      - database
    ports:
      - '3000:3000'      
    environment:
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWS: ${DB_PWS}
      DB_NAME: ${DB_NAME}

  frontend:
    build: ./packages/frontend
    depends_on:
      - backend    
    ports:
      - '80:80'
    environment:
      VITE_API_BASE_URL : ${API_BASE_URL}
    links:
        - backend

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
