version: '3.9'

services:
  backend:
    build: ./packages/backend
    depends_on:
      - database
    ports:
      - '3000:3000'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWS: ${DB_PWS}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}

  frontend:
    build:
      context: ./packages/frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - backend
    ports:
      - '80:80'

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWS}
      POSTGRES_DB: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
